import pymel.core as pm

### Create Locators

#  TODO // Make a fool check for if there is a naming conflict 

def createArmLocs():
    pm.spaceLocator(name="Loc_Shoulder_l_arm")
    pm.move(0,10,0)
    pm.spaceLocator(name="Loc_Up_l_arm")
    pm.move(2,10,0)
    pm.spaceLocator(name="Loc_Low_l_arm")
    pm.move(7,10,-1)
    pm.spaceLocator(name="Loc_LowEnd_l_arm")
    pm.move(12,10,0)

    temp=(pm.spaceLocator(name="Loc_pinky00_l_arm"))
    pm.move(14,10,-1)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_pinky01_l_arm")
    pm.move(15,10,-1)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_pinky02_l_arm")
    pm.move(16,10,-1)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_pinky03_l_arm")
    pm.move(17,10,-1)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_ring00_l_arm")
    pm.move(14,10,-0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_ring01_l_arm")
    pm.move(15,10,-0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_ring02_l_arm")
    pm.move(16,10,-0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_ring03_l_arm")
    pm.move(17,10,-0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_middle00_l_arm")
    pm.move(14,10,0)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_middle01_l_arm")
    pm.move(15,10,0)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_middle02_l_arm")
    pm.move(16,10,0)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_middle03_l_arm")
    pm.move(17,10,0)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_index00_l_arm")
    pm.move(14,10,0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_index01_l_arm")
    pm.move(15,10,0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_index02_l_arm")
    pm.move(16,10,0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_index03_l_arm")
    pm.move(17,10,0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_thumb00_l_arm")
    pm.move(13,10,1)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_thumb01_l_arm")
    pm.move(13,10,1.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_thumb02_l_arm")
    pm.move(13,10,2)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_thumb03_l_arm")
    pm.move(13,10,2.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))

createArmLocs()