import pymel.core as pm

### Create Locators

#  TODO // Make a fool check for if there is a naming conflict 
whicharm="r_arm"

def createArmLocs():
    pm.spaceLocator(name="Loc_Shoulder_"+whicharm)
    pm.move(0,10,0)
    pm.spaceLocator(name="Loc_Up_"+whicharm)
    pm.move(2,10,0)
    pm.spaceLocator(name="Loc_Low_"+whicharm)
    pm.move(7,10,-1)
    pm.spaceLocator(name="Loc_LowEnd_"+whicharm)
    pm.move(12,10,0)

    temp=(pm.spaceLocator(name="Loc_pinky00_"+whicharm))
    pm.move(14,10,-1)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_pinky01_"+whicharm)
    pm.move(15,10,-1)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_pinky02_"+whicharm)
    pm.move(16,10,-1)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_pinky03_"+whicharm)
    pm.move(17,10,-1)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_ring00_"+whicharm)
    pm.move(14,10,-0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_ring01_"+whicharm)
    pm.move(15,10,-0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_ring02_"+whicharm)
    pm.move(16,10,-0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_ring03_"+whicharm)
    pm.move(17,10,-0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_middle00_"+whicharm)
    pm.move(14,10,0)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_middle01_"+whicharm)
    pm.move(15,10,0)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_middle02_"+whicharm)
    pm.move(16,10,0)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_middle03_"+whicharm)
    pm.move(17,10,0)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_index00_"+whicharm)
    pm.move(14,10,0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_index01_"+whicharm)
    pm.move(15,10,0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_index02_"+whicharm)
    pm.move(16,10,0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_index03_"+whicharm)
    pm.move(17,10,0.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_thumb00_"+whicharm)
    pm.move(13,10,1)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_thumb01_"+whicharm)
    pm.move(13,10,1.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_thumb02_"+whicharm)
    pm.move(13,10,2)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))
    temp=pm.spaceLocator(name="Loc_thumb03_"+whicharm)
    pm.move(13,10,2.5)
    pm.setAttr(temp.getShape()+".localScale",(0.1,0.1,0.1))

createArmLocs()