# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kinematics_settings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(557, 671)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 80, 389, 451))
        self.action_settings_formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.action_settings_formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.action_settings_formLayout.setLabelAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.action_settings_formLayout.setContentsMargins(0, 0, 0, 0)

        self.guide_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.guide_lbl.setText("Guides:")
        self.action_settings_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.guide_lbl)

        self.guides_hLay = QtWidgets.QHBoxLayout()

        self.from_file_radioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.from_file_radioButton.setText("From File")
        self.guides_hLay.addWidget(self.from_file_radioButton)

        self.from_current_scene_radioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.from_current_scene_radioButton.setText("From Current Scene")
        self.guides_hLay.addWidget(self.from_current_scene_radioButton)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.guides_hLay.addItem(spacerItem)

        self.action_settings_formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.guides_hLay)

        self.file_path_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.file_path_lbl.setText("File Path:")
        self.action_settings_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.file_path_lbl)

        self.file_path_hLay = QtWidgets.QHBoxLayout()
        self.file_path_le = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.file_path_hLay.addWidget(self.file_path_le)
        self.browse_path_pb = QtWidgets.QPushButton(self.formLayoutWidget)
        self.file_path_hLay.addWidget(self.browse_path_pb)
        self.action_settings_formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.file_path_hLay)
        self.guide_roots_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.guide_roots_lbl.setText("Guide Roots:")
        self.action_settings_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.guide_roots_lbl)

        self.guide_roots_hLay = QtWidgets.QHBoxLayout()
        self.guide_roots_le = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.guide_roots_hLay.addWidget(self.guide_roots_le)
        self.get_guide_roots_pb = QtWidgets.QPushButton(self.formLayoutWidget)
        self.guide_roots_hLay.addWidget(self.get_guide_roots_pb)
        self.action_settings_formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.guide_roots_hLay)

        self.create_auto_sw_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.create_auto_sw_lbl.setText("Create Auto Switchers:")
        self.action_settings_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.create_auto_sw_lbl)
        self.create_auto_switchers_hLay = QtWidgets.QHBoxLayout()
        
        self.auto_sw_on_radioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.auto_sw_on_radioButton.setText("On")
        self.create_auto_switchers_hLay.addWidget(self.auto_sw_on_radioButton)
        self.auto_sw_off_radioButton = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.auto_sw_off_radioButton.setText("Off")
        self.create_auto_switchers_hLay.addWidget(self.auto_sw_off_radioButton)
        
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.create_auto_switchers_hLay.addItem(spacerItem1)
        self.action_settings_formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.create_auto_switchers_hLay)
        
        self.anchors_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.anchors_lbl.setText("Anchors:")
        self.action_settings_formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.anchors_lbl)
        
        self.anchors_le = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.action_settings_formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.anchors_le)
        
        self.anchor_locations_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.anchor_locations_lbl.setText("Anchor Locations:")
        self.action_settings_formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.anchor_locations_lbl)
        
        self.anchor_locations_le = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.action_settings_formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.anchor_locations_le)
        
        self.after_action_lbl = QtWidgets.QLabel(self.formLayoutWidget)
        self.after_action_lbl.setText("After Action:")
        self.action_settings_formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.after_action_lbl)
        
        self.after_action_combo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.after_action_combo.setObjectName("after_action_combo")
        self.after_action_combo.addItem("")
        self.after_action_combo.setItemText(0, "Delete Guides")
        self.after_action_combo.addItem("")
        self.after_action_combo.setItemText(1, "Hide Guides")
        self.after_action_combo.addItem("")
        self.after_action_combo.setItemText(2, "Do Nothing")
        self.action_settings_formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.after_action_combo)



