# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI_v001.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_trigger_MainWindow(object):
    def setupUi(self, trigger_MainWindow):
        trigger_MainWindow.setObjectName("trigger_MainWindow")
        trigger_MainWindow.resize(570, 385)
        trigger_MainWindow.setWindowTitle("TRigger")
        trigger_MainWindow.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(trigger_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralWidget_vLay = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralWidget_vLay.setContentsMargins(0, 0, 0, 0)
        self.centralWidget_vLay.setSpacing(0)
        self.centralWidget_vLay.setObjectName("centralWidget_vLay")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.guides_tab = QtWidgets.QWidget()
        self.guides_tab.setToolTip("")
        self.guides_tab.setStatusTip("")
        self.guides_tab.setWhatsThis("")
        self.guides_tab.setAccessibleName("")
        self.guides_tab.setAccessibleDescription("")
        self.guides_tab.setObjectName("guides_tab")

        self.guides_tab_vlay = QtWidgets.QVBoxLayout(self.guides_tab)
        self.guides_tab_vlay.setContentsMargins(0, 0, 0, 0)
        self.guides_tab_vlay.setSpacing(0)
        self.guides_tab_vlay.setObjectName("guides_tab_vlay")
        self.guides_splitter = QtWidgets.QSplitter(self.guides_tab)
        self.guides_splitter.setToolTip("")
        self.guides_splitter.setStatusTip("")
        self.guides_splitter.setWhatsThis("")
        self.guides_splitter.setAccessibleName("")
        self.guides_splitter.setAccessibleDescription("")
        self.guides_splitter.setLineWidth(1)
        self.guides_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.guides_splitter.setObjectName("guides_splitter")
        self.L_guides_scrollArea = QtWidgets.QScrollArea(self.guides_splitter)
        self.L_guides_scrollArea.setToolTip("")
        self.L_guides_scrollArea.setStatusTip("")
        self.L_guides_scrollArea.setWhatsThis("")
        self.L_guides_scrollArea.setAccessibleName("")
        self.L_guides_scrollArea.setAccessibleDescription("")
        self.L_guides_scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.L_guides_scrollArea.setWidgetResizable(True)
        self.L_guides_scrollArea.setObjectName("L_guides_scrollArea")
        self.L_guides_WidgetContents = QtWidgets.QWidget()
        self.L_guides_WidgetContents.setGeometry(QtCore.QRect(0, 0, 278, 316))
        self.L_guides_WidgetContents.setObjectName("L_guides_WidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.L_guides_WidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.L_guides_vLay = QtWidgets.QVBoxLayout()
        self.L_guides_vLay.setObjectName("L_guides_vLay")
        self.module_guides_lbl = QtWidgets.QLabel(self.L_guides_WidgetContents)
        self.module_guides_lbl.setToolTip("")
        self.module_guides_lbl.setStatusTip("")
        self.module_guides_lbl.setWhatsThis("")
        self.module_guides_lbl.setAccessibleName("")
        self.module_guides_lbl.setAccessibleDescription("")
        self.module_guides_lbl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.module_guides_lbl.setFrameShadow(QtWidgets.QFrame.Plain)
        self.module_guides_lbl.setText("Module Guides")
        self.module_guides_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.module_guides_lbl.setObjectName("module_guides_lbl")
        self.L_guides_vLay.addWidget(self.module_guides_lbl)
        self.module_button2 = QtWidgets.QPushButton(self.L_guides_WidgetContents)
        self.module_button2.setToolTip("")
        self.module_button2.setStatusTip("")
        self.module_button2.setWhatsThis("")
        self.module_button2.setAccessibleName("")
        self.module_button2.setAccessibleDescription("")
        self.module_button2.setObjectName("module_button2")
        self.L_guides_vLay.addWidget(self.module_button2)
        self.module_button3 = QtWidgets.QPushButton(self.L_guides_WidgetContents)
        self.module_button3.setToolTip("")
        self.module_button3.setStatusTip("")
        self.module_button3.setWhatsThis("")
        self.module_button3.setAccessibleName("")
        self.module_button3.setAccessibleDescription("")
        self.module_button3.setObjectName("module_button3")
        self.L_guides_vLay.addWidget(self.module_button3)
        self.module_button1 = QtWidgets.QPushButton(self.L_guides_WidgetContents)
        self.module_button1.setToolTip("")
        self.module_button1.setStatusTip("")
        self.module_button1.setWhatsThis("")
        self.module_button1.setAccessibleName("")
        self.module_button1.setAccessibleDescription("")
        self.module_button1.setObjectName("module_button1")
        self.L_guides_vLay.addWidget(self.module_button1)
        self.module_button4 = QtWidgets.QPushButton(self.L_guides_WidgetContents)
        self.module_button4.setToolTip("")
        self.module_button4.setStatusTip("")
        self.module_button4.setWhatsThis("")
        self.module_button4.setAccessibleName("")
        self.module_button4.setAccessibleDescription("")
        self.module_button4.setObjectName("module_button4")
        self.L_guides_vLay.addWidget(self.module_button4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.L_guides_vLay.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.L_guides_vLay)
        self.L_guides_scrollArea.setWidget(self.L_guides_WidgetContents)
        self.R_guides_scrollArea = QtWidgets.QScrollArea(self.guides_splitter)
        self.R_guides_scrollArea.setToolTip("")
        self.R_guides_scrollArea.setStatusTip("")
        self.R_guides_scrollArea.setWhatsThis("")
        self.R_guides_scrollArea.setAccessibleName("")
        self.R_guides_scrollArea.setAccessibleDescription("")
        self.R_guides_scrollArea.setWidgetResizable(True)
        self.R_guides_scrollArea.setObjectName("R_guides_scrollArea")
        self.R_guides_WidgetContents = QtWidgets.QWidget()
        self.R_guides_WidgetContents.setGeometry(QtCore.QRect(0, 0, 277, 316))
        self.R_guides_WidgetContents.setToolTip("")
        self.R_guides_WidgetContents.setStatusTip("")
        self.R_guides_WidgetContents.setWhatsThis("")
        self.R_guides_WidgetContents.setAccessibleName("")
        self.R_guides_WidgetContents.setAccessibleDescription("")
        self.R_guides_WidgetContents.setObjectName("R_guides_WidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.R_guides_WidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.module_settings_formLayout = QtWidgets.QFormLayout()
        self.module_settings_formLayout.setObjectName("module_settings_formLayout")
        self.setting1_lbl = QtWidgets.QLabel(self.R_guides_WidgetContents)
        self.setting1_lbl.setToolTip("")
        self.setting1_lbl.setStatusTip("")
        self.setting1_lbl.setWhatsThis("")
        self.setting1_lbl.setAccessibleName("")
        self.setting1_lbl.setAccessibleDescription("")
        self.setting1_lbl.setObjectName("setting1_lbl")
        self.module_settings_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.setting1_lbl)
        self.setting1_le = QtWidgets.QLineEdit(self.R_guides_WidgetContents)
        self.setting1_le.setToolTip("")
        self.setting1_le.setStatusTip("")
        self.setting1_le.setWhatsThis("")
        self.setting1_le.setAccessibleName("")
        self.setting1_le.setAccessibleDescription("")
        self.setting1_le.setObjectName("setting1_le")
        self.module_settings_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.setting1_le)
        self.setting2_lbl = QtWidgets.QLabel(self.R_guides_WidgetContents)
        self.setting2_lbl.setToolTip("")
        self.setting2_lbl.setStatusTip("")
        self.setting2_lbl.setWhatsThis("")
        self.setting2_lbl.setAccessibleName("")
        self.setting2_lbl.setAccessibleDescription("")
        self.setting2_lbl.setObjectName("setting2_lbl")
        self.module_settings_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.setting2_lbl)
        self.setting2_combo = QtWidgets.QComboBox(self.R_guides_WidgetContents)
        self.setting2_combo.setToolTip("")
        self.setting2_combo.setStatusTip("")
        self.setting2_combo.setWhatsThis("")
        self.setting2_combo.setAccessibleName("")
        self.setting2_combo.setAccessibleDescription("")
        self.setting2_combo.setObjectName("setting2_combo")
        self.module_settings_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.setting2_combo)
        self.setting3_lbl = QtWidgets.QLabel(self.R_guides_WidgetContents)
        self.setting3_lbl.setToolTip("")
        self.setting3_lbl.setStatusTip("")
        self.setting3_lbl.setWhatsThis("")
        self.setting3_lbl.setAccessibleName("")
        self.setting3_lbl.setAccessibleDescription("")
        self.setting3_lbl.setObjectName("setting3_lbl")
        self.module_settings_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.setting3_lbl)
        self.setting3_chk = QtWidgets.QCheckBox(self.R_guides_WidgetContents)
        self.setting3_chk.setToolTip("")
        self.setting3_chk.setStatusTip("")
        self.setting3_chk.setWhatsThis("")
        self.setting3_chk.setAccessibleName("")
        self.setting3_chk.setAccessibleDescription("")
        self.setting3_chk.setObjectName("setting3_chk")
        self.module_settings_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.setting3_chk)
        self.verticalLayout_2.addLayout(self.module_settings_formLayout)
        self.R_guides_scrollArea.setWidget(self.R_guides_WidgetContents)
        self.guides_tab_vlay.addWidget(self.guides_splitter)
        self.tabWidget.addTab(self.guides_tab, "Guides")
        self.rigging_tab = QtWidgets.QWidget()
        self.rigging_tab.setToolTip("")
        self.rigging_tab.setStatusTip("")
        self.rigging_tab.setWhatsThis("")
        self.rigging_tab.setAccessibleName("")
        self.rigging_tab.setAccessibleDescription("")
        self.rigging_tab.setObjectName("rigging_tab")
        self.tabWidget.addTab(self.rigging_tab, "Rigging")
        self.centralWidget_vLay.addWidget(self.tabWidget)
        trigger_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(trigger_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 21))
        self.menubar.setToolTip("")
        self.menubar.setStatusTip("")
        self.menubar.setAccessibleName("")
        self.menubar.setAccessibleDescription("")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setToolTip("")
        self.menuFile.setStatusTip("")
        self.menuFile.setAccessibleName("")
        self.menuFile.setAccessibleDescription("")
        self.menuFile.setObjectName("menuFile")
        trigger_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(trigger_MainWindow)
        self.statusbar.setToolTip("")
        self.statusbar.setStatusTip("")
        self.statusbar.setWhatsThis("")
        self.statusbar.setAccessibleName("")
        self.statusbar.setObjectName("statusbar")
        trigger_MainWindow.setStatusBar(self.statusbar)
        self.Import_Guides_action = QtWidgets.QAction(trigger_MainWindow)
        self.Import_Guides_action.setText("Import Guides")
        self.Import_Guides_action.setIconText("Import Guides")
        self.Import_Guides_action.setToolTip("Import Guides")
        self.Import_Guides_action.setStatusTip("")
        self.Import_Guides_action.setWhatsThis("")
        self.Import_Guides_action.setObjectName("Import_Guides_action")
        self.Export_Guides_action = QtWidgets.QAction(trigger_MainWindow)
        self.Export_Guides_action.setText("Export Guides")
        self.Export_Guides_action.setIconText("Export Guides")
        self.Export_Guides_action.setToolTip("Export Guides")
        self.Export_Guides_action.setStatusTip("")
        self.Export_Guides_action.setWhatsThis("")
        self.Export_Guides_action.setObjectName("Export_Guides_action")
        self.Save_Session_action = QtWidgets.QAction(trigger_MainWindow)
        self.Save_Session_action.setText("Save Session")
        self.Save_Session_action.setIconText("Save Session")
        self.Save_Session_action.setToolTip("Save Session")
        self.Save_Session_action.setStatusTip("")
        self.Save_Session_action.setWhatsThis("")
        self.Save_Session_action.setObjectName("Save_Session_action")
        self.Load_Session_action = QtWidgets.QAction(trigger_MainWindow)
        self.Load_Session_action.setText("Load Session")
        self.Load_Session_action.setIconText("Load Session")
        self.Load_Session_action.setToolTip("Load Session")
        self.Load_Session_action.setStatusTip("")
        self.Load_Session_action.setWhatsThis("")
        self.Load_Session_action.setObjectName("Load_Session_action")
        self.New_Session_action = QtWidgets.QAction(trigger_MainWindow)
        self.New_Session_action.setText("New Session")
        self.New_Session_action.setIconText("New Session")
        self.New_Session_action.setToolTip("New Session")
        self.New_Session_action.setStatusTip("")
        self.New_Session_action.setWhatsThis("")
        self.New_Session_action.setObjectName("New_Session_action")
        self.menuFile.addAction(self.New_Session_action)
        self.menuFile.addAction(self.Save_Session_action)
        self.menuFile.addAction(self.Load_Session_action)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.Import_Guides_action)
        self.menuFile.addAction(self.Export_Guides_action)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(trigger_MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(trigger_MainWindow)

    def retranslateUi(self, trigger_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.module_button2.setText(_translate("trigger_MainWindow", "PushButton"))
        self.module_button3.setText(_translate("trigger_MainWindow", "PushButton"))
        self.module_button1.setText(_translate("trigger_MainWindow", "PushButton"))
        self.module_button4.setText(_translate("trigger_MainWindow", "PushButton"))
        self.setting1_lbl.setText(_translate("trigger_MainWindow", "Setting1"))
        self.setting2_lbl.setText(_translate("trigger_MainWindow", "Setting2"))
        self.setting3_lbl.setText(_translate("trigger_MainWindow", "Setting3"))
        self.menuFile.setTitle(_translate("trigger_MainWindow", "File"))
