"""Contains data for all modules"""

# This is the bare minimum guide joint names for all modules
#
# MODULE_DICTIONARY = {
#     "arm": ["Collar", "Shoulder", "Elbow", "Hand"],
#     "leg": ["LegRoot", "Hip", "Knee", "Foot", "Ball", "HeelPV", "ToePV", "BankIN", "BankOUT"],
#     "spine": ["SpineRoot", "Spine", "SpineEnd"],
#     "neck": ["NeckRoot", "Neck", "Head", "Jaw", "HeadEnd"],
#     "tail": ["TailRoot", "Tail"],
#     "finger": ["FingerRoot", "Finger"],
#     "tentacle": ["TentacleRoot", "Tentacle", "TentacleEnd"],
#     "root": ["Root"]
# }

MODULE_DICTIONARY = {
    "arm": {
        "members": ["Collar", "Shoulder", "Elbow", "Hand"],
        "properties": [],
        "multi_guide": None,
        "sided": True,
    },
    "leg": {
        "members": ["LegRoot", "Hip", "Knee", "Foot", "Ball", "HeelPV", "ToePV", "BankIN", "BankOUT"],
        "properties": [],
        "multi_guide": None,
        "sided": True,
    },
    "spine": {
        "members": ["SpineRoot", "Spine", "SpineEnd"],
        "properties": [{"attr_name": "resolution",
                        "nice_name": "Resolution",
                        "attr_type": "long",
                        "min_value": 1,
                        "max_value": 9999,
                        "default_value": 4,
                        },
                       {"attr_name": "dropoff",
                        "nice_name": "Drop_Off",
                        "attr_type": "float",
                        "min_value": 0.1,
                        "max_value": 5.0,
                        "default_value": 1.0,
                        },
                       ],
        "multi_guide": "Spine",
        "sided": False,
    },
    "head": {
        "members": ["NeckRoot", "Neck", "Head", "Jaw", "HeadEnd"],
        "properties": [{"attr_name": "resolution",
                        "nice_name": "Resolution",
                        "attr_type": "long",
                        "min_value": 1,
                        "max_value": 9999,
                        "default_value": 4,
                        },
                       {"attr_name": "dropoff",
                        "nice_name": "Drop_Off",
                        "attr_type": "float",
                        "min_value": 0.1,
                        "max_value": 5.0,
                        "default_value": 1.0,
                        },
                       ],
        "multi_guide": "Neck",
        "sided": False,
    },
    "tail": {
        "members": ["TailRoot", "Tail"],
        "properties": [],
        "multi_guide": "Tail",
        "sided": True,
    },
    "finger": {
        "members": ["FingerRoot", "Finger"],
        "properties": [],
        "multi_guide": "Finger",
        "sided": True,
    },
    "tentacle": {
        "members":["TentacleRoot", "Tentacle", "TentacleEnd"],
        "properties": [{"attr_name": "contRes",
                        "nice_name": "Ctrl_Res",
                        "attr_type": "long",
                        "min_value": 1,
                        "max_value": 9999,
                        "default_value": 5,
                        },
                       {"attr_name": "jointRes",
                        "nice_name": "Joint_Res",
                        "attr_type": "long",
                        "min_value": 1,
                        "max_value": 9999,
                        "default_value": 25,
                        },
                       {"attr_name": "deformerRes",
                        "nice_name": "Deformer_Resolution",
                        "attr_type": "long",
                        "min_value": 1,
                        "max_value": 9999,
                        "default_value": 25,
                        },
                       {"attr_name": "dropoff",
                        "nice_name": "Drop_Off",
                        "attr_type": "float",
                        "min_value": 0.1,
                        "max_value": 5.0,
                        "default_value": 1.0,
                        },
                       ],
        "multi_guide": "Tentacle",
        "sided": True,
    },
    "root": {
        "members": ["Root"],
        "properties": [],
        "multi_guide": None,
        "sided": False,
    },
}


# MODULE_DICTIONARY = {
#     "arm": {
#         "members": ["Collar", "Shoulder", "Elbow", "Hand"],
#         "properties": [],
#         "multi_guide": None,
#     },
#     "leg": {
#         "members": ["LegRoot", "Hip", "Knee", "Foot", "Ball", "HeelPV", "ToePV", "BankIN", "BankOUT"],
#         "properties": [],
#         "multi_guide": None,
#     },
#     "spine": {
#         "members": ["SpineRoot", "Spine", "SpineEnd"],
#         "properties": ["resolution", "dropoff"],
#         "multi_guide": "Spine",
#     },
#     "head": {
#         "members": ["NeckRoot", "Neck", "Head", "Jaw", "HeadEnd"],
#         "properties": ["resolution", "dropoff"],
#         "multi_guide": "Neck",
#     },
#     "tail": {
#         "members": ["TailRoot", "Tail"],
#         "properties": [],
#         "multi_guide": "Tail",
#     },
#     "finger": {
#         "members": ["FingerRoot", "Finger"],
#         "properties": [],
#         "multi_guide": "Finger",
#     },
#     "tentacle": {
#         "members":["TentacleRoot", "Tentacle", "TentacleEnd"],
#         "properties": ["contRes", "jointRes", "deformerRes", "dropoff"],
#         "multi_guide": "Tentacle",
#     },
#     "root": {
#         "members": ["Root"],
#         "properties": [],
#         "multi_guide": None,
#     },
# }