# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trigger_tool_UI_v001.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_trigger_tool(object):
    def setupUi(self, trigger_tool):
        trigger_tool.setObjectName("trigger_tool")
        trigger_tool.resize(264, 237)
        trigger_tool.setWindowTitle("Trigger Tool v0.1")
        self.main_vlay = QtWidgets.QVBoxLayout(trigger_tool)
        self.main_vlay.setContentsMargins(5, 5, 5, 5)
        self.main_vlay.setSpacing(5)
        self.main_vlay.setObjectName("main_vlay")

        self.select_and_pose_hlay = QtWidgets.QHBoxLayout()

        self.select_gbox = QtWidgets.QGroupBox(trigger_tool)
        self.select_gbox.setTitle("Select")

        self.select_grp_vlay = QtWidgets.QVBoxLayout(self.select_gbox)
        self.select_grp_vlay.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.select_grp_vlay.setContentsMargins(5, 0, 0, 5)
        self.select_grp_vlay.setSpacing(5)

        self.select_vlay = QtWidgets.QVBoxLayout()
        self.select_vlay.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.select_vlay.setSpacing(5)

        self.all_body_pb = QtWidgets.QPushButton(self.select_gbox)
        self.all_body_pb.setText("All Body")
        self.select_vlay.addWidget(self.all_body_pb)

        self.all_face_pb = QtWidgets.QPushButton(self.select_gbox)
        self.all_face_pb.setText("All Face")
        self.select_vlay.addWidget(self.all_face_pb)

        self.select_mirror_pb = QtWidgets.QPushButton(self.select_gbox)
        self.select_mirror_pb.setText("Select Mirror")
        self.select_vlay.addWidget(self.select_mirror_pb)

        self.all_tweakers_pb = QtWidgets.QPushButton(self.select_gbox)
        self.all_tweakers_pb.setText("All Tweakers")
        self.select_vlay.addWidget(self.all_tweakers_pb)

        self.select_grp_vlay.addLayout(self.select_vlay)
        self.select_and_pose_hlay.addWidget(self.select_gbox)

        self.pose_gbox = QtWidgets.QGroupBox(trigger_tool)
        self.pose_gbox.setTitle("Pose")

        self.pose_grp_vlay = QtWidgets.QVBoxLayout(self.pose_gbox)
        self.pose_grp_vlay.setContentsMargins(5, 0, 5, 0)
        self.pose_grp_vlay.setSpacing(5)

        self.pose_ctrls_vlay = QtWidgets.QVBoxLayout()
        self.pose_ctrls_vlay.setSpacing(5)

        self.copy_mirror_pb = QtWidgets.QPushButton(self.pose_gbox)
        self.copy_mirror_pb.setText("Copy Mirror")
        self.pose_ctrls_vlay.addWidget(self.copy_mirror_pb)

        self.swap_mirror_pb = QtWidgets.QPushButton(self.pose_gbox)
        self.swap_mirror_pb.setText("Swap Mirror")
        self.pose_ctrls_vlay.addWidget(self.swap_mirror_pb)

        self.zero_tpose_pb = QtWidgets.QPushButton(self.pose_gbox)
        self.zero_tpose_pb.setText(" Zero T-Pose")
        self.pose_ctrls_vlay.addWidget(self.zero_tpose_pb)

        self.reset_tpose_pb = QtWidgets.QPushButton(self.pose_gbox)
        self.reset_tpose_pb.setText("Reset T-Pose")

        self.pose_ctrls_vlay.addWidget(self.reset_tpose_pb)

        self.pose_grp_vlay.addLayout(self.pose_ctrls_vlay)

        self.select_and_pose_hlay.addWidget(self.pose_gbox)

        self.main_vlay.addLayout(self.select_and_pose_hlay)

        self.settings_gbox = QtWidgets.QGroupBox(trigger_tool)
        self.settings_gbox.setTitle("Settings")

        self.settings_grp_vlay = QtWidgets.QVBoxLayout(self.settings_gbox)
        self.settings_grp_vlay.setContentsMargins(5, 0, 5, 0)
        self.settings_grp_vlay.setSpacing(5)

        self.namespace_hlay = QtWidgets.QHBoxLayout()
        self.namespace_hlay.setSpacing(0)

        self.namespace_lbl = QtWidgets.QLabel(self.settings_gbox)
        self.namespace_lbl.setText("Namespace")
        self.namespace_hlay.addWidget(self.namespace_lbl)

        self.namespace_combo = QtWidgets.QComboBox(self.settings_gbox)
        self.namespace_hlay.addWidget(self.namespace_combo)
        self.settings_grp_vlay.addLayout(self.namespace_hlay)

        self.mirror_mode_hlay = QtWidgets.QHBoxLayout()
        self.mirror_mode_hlay.setSpacing(0)

        self.mirror_mode_lbl = QtWidgets.QLabel(self.settings_gbox)
        self.mirror_mode_lbl.setText("Mirror Mode")
        self.mirror_mode_hlay.addWidget(self.mirror_mode_lbl)

        self.mirror_mode_combo = QtWidgets.QComboBox(self.settings_gbox)
        self.mirror_mode_hlay.addWidget(self.mirror_mode_combo)

        self.settings_grp_vlay.addLayout(self.mirror_mode_hlay)

        self.side_tags_hlay = QtWidgets.QHBoxLayout()
        self.side_tags_hlay.setSpacing(0)

        self.side_tags_lbl = QtWidgets.QLabel(self.settings_gbox)
        self.side_tags_lbl.setText("Side Tags")
        self.side_tags_hlay.addWidget(self.side_tags_lbl)

        self.side_tags_combo = QtWidgets.QComboBox(self.settings_gbox)
        self.side_tags_hlay.addWidget(self.side_tags_combo)

        self.settings_grp_vlay.addLayout(self.side_tags_hlay)

        self.main_vlay.addWidget(self.settings_gbox)

